events {}

http {
    upstream frontend_service {
        server frontend:80;
    }

    upstream backend_service {
        server backend:5000;
    }

    upstream transactions_service {
        server transactions:4000;
    }

    server {
        listen 80;

        # Transactions JS API
        location /api/transactions/ {
            proxy_pass http://transactions_service;
        }

        # Flask backend API
        location /api/ {
            proxy_pass http://backend_service;
        }

        # Studentportfolio frontend
        location / {
            proxy_pass http://frontend_service;
        }
    }
}